function plotPVProfile(pathData)

    pathAnal = fullfile(pathData,'Analysis\');
    
    load(fullfile(pathData,'initPeakIntAllRec.mat'),'modInt1AL');
    load(fullfile(pathData,'initPeakPyrIntAllRec.mat'),'InitAll','IntRise');
    
    plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                InitAll.avgFRProfileInt(IntRise.idxRise{3},:),...
                InitAll.avgFRProfileBadInt(IntRise.idxRiseBadBad{3},:),...
                ['FR IntRise Good/Bad C' num2str(3)],...
                ['Int_FRProfileIntRiseGoodBadC' num2str(3)],...
                pathAnal,[0 30],[{'Good'} {'Bad'}])