function plotSSTProfile(pathData)

    pathAnal = fullfile(pathData,'Analysis\');
    
    load(fullfile(pathData,'initPeakIntAllRec.mat'),'modInt1AL');
    load(fullfile(pathData,'initPeakPyrIntAllRec.mat'),'InitAll','IntRise');
    
    plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                InitAll.avgFRProfileInt(IntRise.idxRise{2},:),...
                InitAll.avgFRProfileBadInt(IntRise.idxRiseBadBad{2},:),...
                ['FR IntRise Good/Bad C' num2str(2)],...
                ['Int_FRProfileIntRiseGoodBadC' num2str(2)],...
                pathAnal,[0 30],[{'Good'} {'Bad'}])