function CompPyrAlignedCorrNoCueVsALPL(pathData)

    pathAnal = fullfile(pathData, 'Analysis\');
    if(exist([pathData '\autoCorrPyrAlignedAllRec_CtrlTr.mat']))
        load([pathData '\autoCorrPyrAlignedAllRec_CtrlTr.mat']);
    end
    
    plotBarsOnly(...
        [mean(noCueVsALPL.ALPLMeanCorrTRunNZField),mean(noCueVsALPL.ALPLMeanCorrTCueNZField)],...
            [std(noCueVsALPL.ALPLMeanCorrTRunNZField)/sqrt(length(noCueVsALPL.ALPLMeanCorrTRunNZField)),...
            std(noCueVsALPL.ALPLMeanCorrTCueNZField)/sqrt(length(noCueVsALPL.ALPLMeanCorrTCueNZField))],...
            '','Mean corr. T NZ Field (Run vs Cue)', ['p=' num2str(noCueVsALPL.pRSMeanCorrTRunCueNZField)],...
            pathAnal,'MeanCorrTNZFieldRunVsCueALPLBar')