function plotPercNeuronsWithField_RunAligned(pathData)

    if(exist([pathData '\initPeakPyrAllRec.mat']))
        load([pathData '\initPeakPyrAllRec.mat']);
    end

    pathAnal = fullfile(pathData,'Analysis\');

    plotBars(numFieldAligned.NoCuePercNeu*100,numFieldAligned.ALPLPercNeu*100,...
            [mean(numFieldAligned.NoCuePercNeu),mean(numFieldAligned.ALPLPercNeu)]*100,...
            [std(numFieldAligned.NoCuePercNeu)/sqrt(length(numFieldAligned.NoCuePercNeu)),...
            std(numFieldAligned.ALPLPercNeu)/sqrt(length(numFieldAligned.ALPLPercNeu))]*100,...
            '','Perc. neurons with field (Aligned)', ['p=' num2str(numFieldAligned.pRSPercField)],...
            pathAnal,'PercFieldAlignedNoCueVsALPLGood')