function plotBehAlignedMeanGoodBadBar(pathData)
% compare behavior of good vs bad trials (bar plots)
% this function is called by PyrBehAlignedAllRec.m
    
    pathAnal = fullfile(pathData, 'Analysis\');
    if(~exist(pathAnal))
        mkdir(pathAnal);
    end

    load([pathData 'behAllRecSel.mat'],'behAlignedMean',...
            'behAlignedMeanStat');  
        
    % mean speed
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood,2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad,2)'/10,...
        behAlignedMeanStat.meanSpeedPerRec,behAlignedMeanStat.stdSpeedPerRec,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRec,...
        [],'Speed (cm/s)',[],'meanSpeedPerRecGoodVsBadBar',...
        pathAnal);

    % distance 30 to 100 cm
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick30to100),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick30to100),2)',...
        behAlignedMeanStat.meanLickPerRec30to100,behAlignedMeanStat.stdLickPerRec30to100,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec30to100,...
        [],'No. licks (30-100 cm)',[],'meanLickPerRecGoodVsBad30to100Bar',...
        pathAnal);
   
end